quarkus:
  http:
    root-path: /mc
    port: 7070
    cors:
      ~: true
      exposed-headers: accept, content-type, x-requested-with, content-disposition
      methods: '*'
      origins: '*'

  hibernate-orm:
    packages: com.vitaliy_challenge.model.entities
    database:
      generation: validate
      default-schema: public
    log:
      sql: false


  datasource:
    db-kind: h2
    username: sa
    password: sa
    jdbc:
      url: jdbc:h2:file:~/IdeaProjects/mc1/src/main/resources/database

  log:
    level: INFO
    min-level: TRACE
    category:
      "org.hibernate":
        level: ERROR

  jackson:
    serialization-inclusion: NON_EMPTY
